-- HammerWhisper — auto-generated by installer
-- https://github.com/jbuch84/HammerWhisper

local recording = false
local ffmpegTask = nil
local indicatorCanvas = nil
local blinkTimer = nil
local durationTimer = nil
local indicatorPos = nil
local recordingStart = nil
local lastTrigger = 0

local defaultBg = { red = 0.12, green = 0.12, blue = 0.12, alpha = 0.88 }
local recordingBg = { red = 0.35, green = 0.05, blue = 0.05, alpha = 0.88 }
local transcribingBg = { red = 0.30, green = 0.24, blue = 0.02, alpha = 0.88 }
local doneBg = { red = 0.06, green = 0.26, blue = 0.06, alpha = 0.88 }

local function showIndicator(labelText, pulse, bgColor)
    if blinkTimer then blinkTimer:stop(); blinkTimer = nil end
    if indicatorCanvas then indicatorCanvas:delete(); indicatorCanvas = nil end

    local color = bgColor or defaultBg
    local w = math.max(52, #labelText * 8 + 24)
    local h = 28

    indicatorCanvas = hs.canvas.new({
        x = indicatorPos.x + 16,
        y = indicatorPos.y + 16,
        w = w, h = h
    })

    indicatorCanvas[1] = {
        type = "rectangle", action = "fill",
        fillColor = color,
        roundedRectRadii = { xRadius = 8, yRadius = 8 },
        frame = { x = 0, y = 0, w = w, h = h },
    }
    indicatorCanvas[2] = {
        type = "text", text = labelText,
        textColor = { white = 1, alpha = 0.9 },
        textSize = 12,
        frame = { x = 10, y = 7, w = w - 16, h = 16 },
    }

    indicatorCanvas:show()

    if pulse then
        local visible = true
        blinkTimer = hs.timer.doEvery(0.6, function()
            visible = not visible
            if indicatorCanvas then indicatorCanvas:alpha(visible and 1.0 or 0.35) end
        end)
    end
end

local function hideIndicator(labelText, duration, bgColor)
    if blinkTimer then blinkTimer:stop(); blinkTimer = nil end
    if durationTimer then durationTimer:stop(); durationTimer = nil end
    if indicatorCanvas then indicatorCanvas:delete(); indicatorCanvas = nil end

    if labelText then
        showIndicator(labelText, false, bgColor)
        hs.timer.doAfter(duration or 1.5, function()
            if indicatorCanvas then indicatorCanvas:delete(); indicatorCanvas = nil end
        end)
    end
end

hs.hotkey.bind({"cmd", "shift"}, "D", function()
    local now = hs.timer.secondsSinceEpoch()
    if now - lastTrigger < 0.5 then return end
    lastTrigger = now

    if not recording then
        indicatorPos = hs.mouse.absolutePosition()
        showIndicator("● 0:00", true, recordingBg)

        recordingStart = hs.timer.secondsSinceEpoch()
        durationTimer = hs.timer.doEvery(1.0, function()
            local elapsed = math.floor(hs.timer.secondsSinceEpoch() - recordingStart)
            local mins = math.floor(elapsed / 60)
            local secs = elapsed % 60
            showIndicator(string.format("● %d:%02d", mins, secs), true, recordingBg)
        end)

        ffmpegTask = hs.task.new("/opt/homebrew/bin/ffmpeg", nil, {
            "-y", "-f", "avfoundation", "-i", ":0",
            "-ac", "1", "-ar", "16000", "/tmp/hammerwhisper.wav"
        })
        ffmpegTask:start()
        recording = true

    else
        hideIndicator("transcribing...", 8, transcribingBg)

        if ffmpegTask and ffmpegTask:isRunning() then ffmpegTask:terminate() end
        ffmpegTask = nil
        recording = false

        hs.timer.doAfter(1.0, function()
            local attrs = hs.fs.attributes("/tmp/hammerwhisper.wav")
            if not attrs or attrs.size < 1000 then
                hideIndicator("nothing recorded", 2, defaultBg)
                return
            end

            local previousClipboard = hs.pasteboard.getContents()

            hs.task.new(
                os.getenv("HOME") .. "/hammerwhisper/dictate",
                function(exitCode, stdOut, stdErr)
                    if exitCode == 0 then
                        hideIndicator("done ✓", 1.5, doneBg)
                        hs.timer.doAfter(0.3, function()
                            hs.pasteboard.setContents(previousClipboard or "")
                        end)
                    else
                        hideIndicator("error", 3, defaultBg)
                        print("dictate error:", stdErr)
                    end
                end, {}
            ):start()
        end)
    end
end)

hs.hotkey.bind({"cmd", "shift"}, "R", function()
    hs.reload()
end)
