#!/bin/bash

set -e

echo ""
echo "🎙️  HammerWhisper Installer"
echo "----------------------------"

# ── 1. Homebrew ──────────────────────────────────────────────────────────────
if ! command -v brew &>/dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    if [ -f /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [ -f /usr/local/bin/brew ]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

if ! command -v brew &>/dev/null; then
    echo "❌ Homebrew installation failed or not found in PATH."
    echo "   Try opening a new terminal and running the installer again."
    exit 1
fi

# ── 2. ffmpeg ────────────────────────────────────────────────────────────────
if ! command -v ffmpeg &>/dev/null; then
    echo "Installing ffmpeg..."
    brew install ffmpeg
fi

# ── 3. Hammerspoon ───────────────────────────────────────────────────────────
if [ ! -d "/Applications/Hammerspoon.app" ]; then
    echo "Installing Hammerspoon..."
    brew install --cask hammerspoon
    echo ""
    echo "⚠️  macOS may block Hammerspoon on first launch."
    echo "   If you see a security warning, go to:"
    echo "   System Settings → Privacy & Security → click 'Open Anyway'"
    echo ""
fi

# ── 4. API key ───────────────────────────────────────────────────────────────
echo ""
echo "Get a free Groq API key at https://console.groq.com (no credit card needed)"
read -p "Paste your API key: " API_KEY </dev/tty
if [ -z "$API_KEY" ]; then
    echo "❌ No API key entered. Exiting."
    exit 1
fi

# ── 5. Optional: custom API URL ──────────────────────────────────────────────
echo ""
read -p "API URL (press Enter to use Groq default): " API_URL </dev/tty
API_URL=${API_URL:-"https://api.groq.com/openai/v1/audio/transcriptions"}

# ── 6. Optional: custom model ────────────────────────────────────────────────
read -p "Model (press Enter for whisper-large-v3): " MODEL </dev/tty
MODEL=${MODEL:-"whisper-large-v3"}

# ── 7. Hotkey modifier ───────────────────────────────────────────────────────
echo ""
echo "Choose a hotkey modifier:"
echo "  1) cmd+shift (default)"
echo "  2) cmd+option"
echo "  3) ctrl+shift"
read -p "Enter 1, 2, or 3 [1]: " MOD_CHOICE </dev/tty

case "$MOD_CHOICE" in
    2) MODIFIER='{"cmd", "option"}' ;;
    3) MODIFIER='{"ctrl", "shift"}' ;;
    *) MODIFIER='{"cmd", "shift"}' ;;
esac

read -p "Hotkey letter (default: D): " HOTKEY </dev/tty
HOTKEY=${HOTKEY:-D}
HOTKEY=$(echo "$HOTKEY" | tr '[:lower:]' '[:upper:]')

# ── 8. Create install directory and config ───────────────────────────────────
mkdir -p ~/hammerwhisper

cat > ~/hammerwhisper/config.json <<EOF
{
    "apiKey": "$API_KEY",
    "apiUrl": "$API_URL",
    "model": "$MODEL",
    "hotkey": "$HOTKEY",
    "modifier": "$MOD_CHOICE"
}
EOF

# ── 9. Download the binary ───────────────────────────────────────────────────
echo ""
echo "Downloading HammerWhisper..."
if ! curl -fsSL https://github.com/jbuch84/HammerWhisper/releases/latest/download/dictate \
        -o ~/hammerwhisper/dictate; then
    echo "❌ Failed to download the dictate binary."
    echo "   Check your internet connection and try again."
    exit 1
fi
xattr -d com.apple.quarantine ~/hammerwhisper/dictate 2>/dev/null || true
chmod +x ~/hammerwhisper/dictate

# ── 10. Write Hammerspoon config ─────────────────────────────────────────────
mkdir -p ~/.hammerspoon

cat > ~/.hammerspoon/init.lua <<LUA
-- HammerWhisper -- auto-generated by installer
-- https://github.com/jbuch84/HammerWhisper

local recording = false
local ffmpegTask = nil
local indicatorCanvas = nil
local blinkTimer = nil
local durationTimer = nil
local indicatorPos = nil
local recordingStart = nil
local lastTrigger = 0

local defaultBg = { red = 0.12, green = 0.12, blue = 0.12, alpha = 0.88 }
local recordingBg = { red = 0.35, green = 0.05, blue = 0.05, alpha = 0.88 }
local transcribingBg = { red = 0.30, green = 0.24, blue = 0.02, alpha = 0.88 }
local doneBg = { red = 0.06, green = 0.26, blue = 0.06, alpha = 0.88 }

local function showIndicator(labelText, pulse, bgColor)
    if blinkTimer then blinkTimer:stop(); blinkTimer = nil end
    if indicatorCanvas then indicatorCanvas:delete(); indicatorCanvas = nil end

    local color = bgColor or defaultBg
    local w = math.max(52, #labelText * 8 + 24)
    local h = 28

    indicatorCanvas = hs.canvas.new({
        x = indicatorPos.x + 16,
        y = indicatorPos.y + 16,
        w = w, h = h
    })

    indicatorCanvas[1] = {
        type = "rectangle", action = "fill",
        fillColor = color,
        roundedRectRadii = { xRadius = 8, yRadius = 8 },
        frame = { x = 0, y = 0, w = w, h = h },
    }
    indicatorCanvas[2] = {
        type = "text", text = labelText,
        textColor = { white = 1, alpha = 0.9 },
        textSize = 12,
        frame = { x = 10, y = 7, w = w - 16, h = 16 },
    }

    indicatorCanvas:show()

    if pulse then
        local visible = true
        blinkTimer = hs.timer.doEvery(0.6, function()
            visible = not visible
            if indicatorCanvas then indicatorCanvas:alpha(visible and 1.0 or 0.35) end
        end)
    end
end

local function hideIndicator(labelText, duration, bgColor)
    if blinkTimer then blinkTimer:stop(); blinkTimer = nil end
    if durationTimer then durationTimer:stop(); durationTimer = nil end
    if indicatorCanvas then indicatorCanvas:delete(); indicatorCanvas = nil end

    if labelText then
        showIndicator(labelText, false, bgColor)
        hs.timer.doAfter(duration or 1.5, function()
            if indicatorCanvas then indicatorCanvas:delete(); indicatorCanvas = nil end
        end)
    end
end

hs.hotkey.bind($MODIFIER, "$HOTKEY", function()
    local now = hs.timer.secondsSinceEpoch()
    if now - lastTrigger < 0.5 then return end
    lastTrigger = now

    if not recording then
        indicatorPos = hs.mouse.absolutePosition()
        showIndicator("● 0:00", true, recordingBg)

        recordingStart = hs.timer.secondsSinceEpoch()
        durationTimer = hs.timer.doEvery(1.0, function()
            local elapsed = math.floor(hs.timer.secondsSinceEpoch() - recordingStart)
            local mins = math.floor(elapsed / 60)
            local secs = elapsed % 60
            showIndicator(string.format("● %d:%02d", mins, secs), true, recordingBg)
        end)

        ffmpegTask = hs.task.new("/opt/homebrew/bin/ffmpeg", nil, {
            "-y", "-f", "avfoundation", "-i", ":0",
            "-ac", "1", "-ar", "16000", "/tmp/hammerwhisper.wav"
        })
        ffmpegTask:start()
        recording = true

    else
        hideIndicator("transcribing...", 8, transcribingBg)

        if ffmpegTask and ffmpegTask:isRunning() then ffmpegTask:terminate() end
        ffmpegTask = nil
        recording = false

        hs.timer.doAfter(1.0, function()
            local attrs = hs.fs.attributes("/tmp/hammerwhisper.wav")
            if not attrs or attrs.size < 1000 then
                hideIndicator("nothing recorded", 2, defaultBg)
                return
            end

            local previousClipboard = hs.pasteboard.getContents()

            hs.task.new(
                os.getenv("HOME") .. "/hammerwhisper/dictate",
                function(exitCode, stdOut, stdErr)
                    if exitCode == 0 then
                        hideIndicator("done ✓", 1.5, doneBg)
                        hs.timer.doAfter(0.3, function()
                            hs.pasteboard.setContents(previousClipboard or "")
                        end)
                    else
                        hideIndicator("error", 3, defaultBg)
                        print("dictate error:", stdErr)
                    end
                end, {}
            ):start()
        end)
    end
end)

hs.hotkey.bind({"cmd", "shift"}, "R", function()
    hs.reload()
end)
LUA

# ── 11. Launch Hammerspoon and reload config ─────────────────────────────────
echo "Launching Hammerspoon..."
open -a Hammerspoon
sleep 2
osascript -e 'tell application "Hammerspoon" to reload config' 2>/dev/null || true

# ── 12. Open Accessibility settings ─────────────────────────────────────────
echo "Opening Accessibility settings..."
sleep 1
open "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"

echo ""
echo "✅ HammerWhisper installed!"
echo ""
echo "⚠️  Two quick things to do before using it:"
echo ""
echo "   1. Grant Accessibility permission:"
echo "      System Settings just opened -- find Hammerspoon and toggle it ON"
echo ""
echo "   2. Enable launch at login so it survives restarts:"
echo "      Click the 🔨 in your menu bar → Preferences → check 'Launch at login'"
echo ""
echo "   Then press $MODIFIER+$HOTKEY anywhere to start dictating."
echo "   (Press once to record, press again to stop and transcribe)"
echo ""
echo "💡 Something not working? Run: ~/hammerwhisper/dictate --check"
echo ""
