#!/bin/bash

set -e

echo ""
echo "⚡ QuickGroq Installer"
echo "----------------------"

# ── 1. Homebrew ──────────────────────────────────────────────────────────────
if ! command -v brew &>/dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    if [ -f /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [ -f /usr/local/bin/brew ]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

if ! command -v brew &>/dev/null; then
    echo "❌ Homebrew installation failed or not found in PATH."
    echo "   Try opening a new terminal and running the installer again."
    exit 1
fi

# ── 2. ffmpeg ────────────────────────────────────────────────────────────────
if ! command -v ffmpeg &>/dev/null; then
    echo "Installing ffmpeg..."
    brew install ffmpeg
fi

# ── 3. Node.js ───────────────────────────────────────────────────────────────
if ! command -v node &>/dev/null; then
    echo "Installing Node.js..."
    brew install node
fi

# Find exact Node path for Hammerspoon
NODE_PATH=$(command -v node)
if [ -z "$NODE_PATH" ]; then
    if [ -f "/opt/homebrew/bin/node" ]; then NODE_PATH="/opt/homebrew/bin/node"
    elif [ -f "/usr/local/bin/node" ]; then NODE_PATH="/usr/local/bin/node"
    else NODE_PATH="node"
    fi
fi

# ── 4. Hammerspoon ───────────────────────────────────────────────────────────
if [ ! -d "/Applications/Hammerspoon.app" ]; then
    echo "Installing Hammerspoon..."
    brew install --cask hammerspoon
    echo ""
    echo "⚠️  macOS may block Hammerspoon on first launch."
    echo "   If you see a security warning, go to:"
    echo "   System Settings → Privacy & Security → click 'Open Anyway'"
    echo ""
fi

# ── 5. API key ───────────────────────────────────────────────────────────────
echo ""
echo "Get a free Groq API key at https://console.groq.com (no credit card needed)"
read -p "Paste your API key: " API_KEY </dev/tty
if [ -z "$API_KEY" ]; then
    echo "❌ No API key entered. Exiting."
    exit 1
fi

# ── 6. Optional: custom API URL ──────────────────────────────────────────────
echo ""
read -p "API URL (press Enter to use Groq default): " API_URL </dev/tty
API_URL=${API_URL:-"https://api.groq.com/openai/v1/audio/transcriptions"}

# ── 7. Optional: custom model ────────────────────────────────────────────────
read -p "Model (press Enter for whisper-large-v3): " MODEL </dev/tty
MODEL=${MODEL:-"whisper-large-v3"}

# ── 8. Hotkey modifier ───────────────────────────────────────────────────────
echo ""
echo "Choose a hotkey modifier:"
echo "  1) cmd+shift (default)"
echo "  2) cmd+option"
echo "  3) ctrl+shift"
read -p "Enter 1, 2, or 3 [1]: " MOD_CHOICE </dev/tty

case "$MOD_CHOICE" in
    2) MODIFIER='{"cmd", "option"}' ;;
    3) MODIFIER='{"ctrl", "shift"}' ;;
    *) MODIFIER='{"cmd", "shift"}' ;;
esac

read -p "Hotkey letter (default: D): " HOTKEY </dev/tty
HOTKEY=${HOTKEY:-D}
HOTKEY=$(echo "$HOTKEY" | tr '[:lower:]' '[:upper:]')

# ── 9. Create install directory and config ───────────────────────────────────
mkdir -p ~/quickgroq

cat > ~/quickgroq/config.json <<EOF
{
    "apiKey": "$API_KEY",
    "apiUrl": "$API_URL",
    "model": "$MODEL",
    "hotkey": "$HOTKEY",
    "modifier": "$MOD_CHOICE"
}
EOF

# ── 10. Download the script ──────────────────────────────────────────────────
echo ""
echo "Downloading QuickGroq script..."
if ! curl -fsSL https://raw.githubusercontent.com/jbuch84/QuickGroq/main/dictate.js \
        -o ~/quickgroq/dictate.js; then
    echo "❌ Failed to download the script."
    echo "   Check your internet connection and try again."
    exit 1
fi

# ── 11. Write Hammerspoon config ─────────────────────────────────────────────
mkdir -p ~/.hammerspoon

cat > ~/.hammerspoon/init.lua <<LUA
-- QuickGroq -- auto-generated by installer
-- https://github.com/jbuch84/QuickGroq

hs.autoLaunch(true)

local recording = false
local ffmpegTask = nil
local indicatorCanvas = nil
local blinkTimer = nil
local durationTimer = nil
local indicatorPos = nil
local recordingStart = nil
local lastTrigger = 0

local bgColor = { red = 0.12, green = 0.12, blue = 0.12, alpha = 0.88 }
local recordingColor = { red = 0.85, green = 0.35, blue = 0.35, alpha = 0.9 }
local transcribingColor = { red = 0.85, green = 0.75, blue = 0.25, alpha = 0.9 }
local doneColor = { red = 0.35, green = 0.80, blue = 0.35, alpha = 0.9 }
local defaultColor = { white = 1, alpha = 0.9 }

local function showIndicator(labelText, pulse, textColor)
    if blinkTimer then blinkTimer:stop(); blinkTimer = nil end
    if indicatorCanvas then indicatorCanvas:delete(); indicatorCanvas = nil end

    local color = textColor or defaultColor
    local w = math.max(52, #labelText * 8 + 24)
    local h = 28

    indicatorCanvas = hs.canvas.new({
        x = indicatorPos.x + 16,
        y = indicatorPos.y + 16,
        w = w, h = h
    })

    indicatorCanvas[1] = {
        type = "rectangle", action = "fill",
        fillColor = bgColor,
        roundedRectRadii = { xRadius = 8, yRadius = 8 },
        frame = { x = 0, y = 0, w = w, h = h },
    }
    indicatorCanvas[2] = {
        type = "text",
        text = hs.styledtext.new(labelText, {
            color = color,
            font = { size = 12 }
        }),
        frame = { x = 10, y = 7, w = w - 16, h = 16 },
    }

    indicatorCanvas:show()

    if pulse then
        local visible = true
        blinkTimer = hs.timer.doEvery(0.6, function()
            visible = not visible
            if indicatorCanvas then indicatorCanvas:alpha(visible and 1.0 or 0.35) end
        end)
    end
end

local function hideIndicator(labelText, duration, textColor)
    if blinkTimer then blinkTimer:stop(); blinkTimer = nil end
    if durationTimer then durationTimer:stop(); durationTimer = nil end
    if indicatorCanvas then indicatorCanvas:delete(); indicatorCanvas = nil end

    if labelText then
        showIndicator(labelText, false, textColor)
        hs.timer.doAfter(duration or 1.5, function()
            if indicatorCanvas then indicatorCanvas:delete(); indicatorCanvas = nil end
        end)
    end
end

hs.hotkey.bind($MODIFIER, "$HOTKEY", function()
    local now = hs.timer.secondsSinceEpoch()
    if now - lastTrigger < 0.5 then return end
    lastTrigger = now

    if not recording then
        indicatorPos = hs.mouse.absolutePosition()
        showIndicator("● 0:00", true, recordingColor)

        recordingStart = hs.timer.secondsSinceEpoch()
        durationTimer = hs.timer.doEvery(1.0, function()
            local elapsed = math.floor(hs.timer.secondsSinceEpoch() - recordingStart)
            local mins = math.floor(elapsed / 60)
            local secs = elapsed % 60
            showIndicator(string.format("● %d:%02d", mins, secs), true, recordingColor)
        end)

        ffmpegTask = hs.task.new("/opt/homebrew/bin/ffmpeg", nil, {
            "-y", "-f", "avfoundation", "-i", ":0",
            "-ac", "1", "-ar", "16000", "/tmp/quickgroq.wav"
        })
        ffmpegTask:start()
        recording = true

    else
        hideIndicator("transcribing...", 8, transcribingColor)

        if ffmpegTask and ffmpegTask:isRunning() then ffmpegTask:terminate() end
        ffmpegTask = nil
        recording = false

        hs.timer.doAfter(1.0, function()
            local attrs = hs.fs.attributes("/tmp/quickgroq.wav")
            if not attrs or attrs.size < 1000 then
                hideIndicator("nothing recorded", 2, defaultColor)
                return
            end

            local previousClipboard = hs.pasteboard.getContents()

            hs.task.new(
                "$NODE_PATH",
                function(exitCode, stdOut, stdErr)
                    if exitCode == 0 then
                        hideIndicator("done ✓", 1.5, doneColor)
                        hs.timer.doAfter(0.3, function()
                            hs.pasteboard.setContents(previousClipboard or "")
                        end)
                    else
                        hideIndicator("error", 3, defaultColor)
                        print("dictate error:", stdErr)
                    end
                end, { os.getenv("HOME") .. "/quickgroq/dictate.js" }
            ):start()
        end)
    end
end)

hs.hotkey.bind({"cmd", "shift"}, "R", function()
    hs.reload()
end)
LUA

# ── 12. Launch Hammerspoon and reload config ─────────────────────────────────
echo "Launching Hammerspoon..."
open -a Hammerspoon
sleep 2
osascript -e 'tell application "Hammerspoon" to reload config' 2>/dev/null || true

# ── 13. Open Accessibility settings ─────────────────────────────────────────
echo "Opening Accessibility settings..."
sleep 1
open "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"

echo ""
echo "✅ QuickGroq installed!"
echo ""
echo "⚠️  One quick thing to do before using it:"
echo ""
echo "   Grant Accessibility permission:"
echo "   System Settings just opened -- find Hammerspoon and toggle it ON"
echo ""
echo "   Then press $MODIFIER+$HOTKEY anywhere to start dictating."
echo "   (Press once to record, press again to stop and transcribe)"
echo ""
echo "💡 Something not working? Run: node ~/quickgroq/dictate.js --check"
echo ""