#!/bin/bash

set -e

exec </dev/tty

echo ""
echo "⚡ QuickGroq Installer for macOS"
echo "--------------------------------"

# ── 1. Homebrew & Dependencies ──────────────────────────────────────────────
if ! command -v brew &>/dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    if [ -f /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [ -f /usr/local/bin/brew ]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

if ! command -v brew &>/dev/null; then
    echo "❌ Homebrew installation failed. Please install it manually at https://brew.sh"
    exit 1
fi

if ! command -v ffmpeg &>/dev/null; then brew install ffmpeg || true; fi
if ! command -v node &>/dev/null; then brew install node || true; fi

# ── Node.js version check (requires v18+ for native fetch) ──────────────────
NODE_PATH=$(command -v node 2>/dev/null || true)
if [ -z "$NODE_PATH" ]; then
    NODE_PATH=$( [ -f "/opt/homebrew/bin/node" ] && echo "/opt/homebrew/bin/node" || echo "/usr/local/bin/node" )
fi

NODE_MAJOR=$("$NODE_PATH" -e "process.stdout.write(String(parseInt(process.version.slice(1))))" 2>/dev/null || echo "0")
if [ "$NODE_MAJOR" -lt 18 ]; then
    echo "⚠️  Node.js v18+ is required (found v${NODE_MAJOR}). Upgrading..."
    brew upgrade node || true
fi

if [ ! -d "/Applications/Hammerspoon.app" ]; then
    echo "Installing Hammerspoon..."
    brew install --cask hammerspoon || true
fi

# ── 2. Configuration Setup ──────────────────────────────────────────────────
echo ""
echo "Get a free Groq API key at https://console.groq.com"
read -r -p "Paste your API key: " API_KEY

if [ -z "$API_KEY" ]; then
    echo "❌ No API key entered. Exiting."
    exit 1
fi

# ── 3. Hotkey Selection ─────────────────────────────────────────────────────
echo ""
echo "Choose your Mac hotkey:"
echo "1) Command + Shift + D (Default)"
echo "2) Option + Shift + D"
echo "3) Command + Shift + 0"
read -r -p "Enter 1, 2, or 3 [1]: " HOTKEY_CHOICE

case "$HOTKEY_CHOICE" in
    2) HS_MODS='["alt", "shift"]'; HS_KEY="d" ;;
    3) HS_MODS='["cmd", "shift"]'; HS_KEY="0" ;;
    *) HS_MODS='["cmd", "shift"]'; HS_KEY="d" ;;
esac

# ── 4. Write Config ─────────────────────────────────────────────────────────
mkdir -p ~/quickgroq

cat > ~/quickgroq/config.json <<EOF
{
  "apiKey": "$API_KEY",
  "apiUrl": "https://api.groq.com/openai/v1/audio/transcriptions",
  "model": "whisper-large-v3",
  "hotkey": {
    "mods": $HS_MODS,
    "key": "$HS_KEY"
  }
}
EOF

# ── 5. Download dictate.js ──────────────────────────────────────────────────
echo ""
echo "Downloading QuickGroq engine..."
curl -sSL "https://raw.githubusercontent.com/jbuch84/QuickGroq/main/dictate.js" -o ~/quickgroq/dictate.js

# ── 6. Write Hammerspoon Config ─────────────────────────────────────────────
if [ -f ~/.hammerspoon/init.lua ]; then
    echo "⚠️  Existing ~/.hammerspoon/init.lua found — backing up to init.lua.bak"
    cp ~/.hammerspoon/init.lua ~/.hammerspoon/init.lua.bak
fi

mkdir -p ~/.hammerspoon

cat > ~/.hammerspoon/init.lua <<LUAEOF
-- QuickGroq — generated by installer
local isRecording = false
local audioFile   = "/tmp/quickgroq.wav"
local nodePath    = "${NODE_PATH}"
local scriptPath  = os.getenv("HOME") .. "/quickgroq/dictate.js"
local mods        = ${HS_MODS}
local key         = "${HS_KEY}"
local recordTask  = nil

hs.hotkey.bind(mods, key, function()
    if not isRecording then
        isRecording = true
        hs.alert.show("🎤 Recording…")
        recordTask = hs.task.new("/opt/homebrew/bin/ffmpeg", nil,
            { "-y", "-f", "avfoundation", "-i", ":0", "-ar", "16000", "-ac", "1", audioFile })
        recordTask:start()
    else
        isRecording = false
        if recordTask then recordTask:terminate() end
        hs.alert.show("⏳ Transcribing…")
        hs.timer.doAfter(0.3, function()
            hs.task.new(nodePath, function(code, out, err)
                if code == 0 and out and #out:gsub("%s+", "") > 0 then
                    hs.pasteboard.setContents(out:gsub("%s+$", ""))
                    hs.eventtap.keyStroke({"cmd"}, "v")
                else
                    hs.alert.show("❌ Transcription failed")
                    if err and #err > 0 then print("QuickGroq error: " .. err) end
                end
            end, { scriptPath }):start()
        end)
    end
end)

hs.alert.show("⚡ QuickGroq ready")
LUAEOF

# ── 7. Reload Hammerspoon & Open Accessibility Prefs ───────────────────────
open -a Hammerspoon 2>/dev/null || true
sleep 2
osascript -e 'tell application "Hammerspoon" to execute lua code "hs.reload()"' 2>/dev/null || true
open "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"

echo ""
echo "✅ QuickGroq installed successfully!"
echo "--------------------------------------------------"
echo "📂 Installation Folder: ~/quickgroq"
echo "⚙️  Config File:         ~/quickgroq/config.json"
echo "🚀 Hammerspoon Config:  ~/.hammerspoon/init.lua"
echo "--------------------------------------------------"
echo "⚠️  Final Step: Enable Hammerspoon in Accessibility settings."
echo ""
